URL functionality
displaynone/youtube-downloader pull request #2
Opened 2019-05-23 16:16 UTC by Doc-Han

Enabling the module to take YouTube Video URL instead of ID.

2019-05-23 16:27 UTC, displaynone requested changes
You shouldn't change that function, instead you should add a new function `getVideoInfoByURL( url )` that, using oEmbed, will get the id and then the data from `getVideoInfo`.

Keep in mind that there are several types of YouTube URLs and your code doesn't work for each of them.

2019-05-23 23:05 UTC, Doc-Han commented
kk I have a Regex that covers most of th URL's.

2019-05-23 23:48 UTC, Doc-Han commented
I think you can test for various URL's. Or should I add test script?

2019-05-24 00:00 UTC, Doc-Han commented
List of example youtube URL's [here](https://gist.github.com/Glurt/ea11b690ba4b1278e049)

2019-05-24 09:04 UTC, displaynone commented
I think you are not using `.editorconfig` or `.eslintrc`

2019-05-24 10:39 UTC, Doc-Han commented
Sorry I'm a beginner who just moved to Intermediate

2019-05-24 11:02 UTC, Doc-Han commented
I think it's linted now

2019-05-24 11:02 UTC, displaynone commented
Don't be sorry for that, nobody's born knowing ;)
Glad to help you and willing to merge your PR :)

2019-05-24 11:12 UTC, Doc-Han commented
eslint said I don't need that escape but I do for the regex to work

2019-05-25 10:19 UTC, Doc-Han commented
Any additional thing I'm to  do?

2019-05-29 18:08 UTC, displaynone approved these changes
@Doc-Han please, review the changes I have implemented

Thanks for your contribution :)

Hope to "see" you again :)

2019-05-29 18:08 UTC, merged

2019-05-31 05:25 UTC, Doc-Han commented on index.js
> +    link = decodeURIComponent(link)+ " ";
so that the regex can match how I wanted